# Generated by Django 5.0.7 on 2024-08-30 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0003_plan_delete_activityplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('duration', models.CharField(max_length=100)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_plans', to='Trip.activity')),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_plans', to='Trip.dayplan')),
            ],
        ),
    ]
