# Generated by Django 5.0.7 on 2024-08-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip', '0004_activityplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='PlaceImage',
        ),
    ]
